In [1]:
#Import Numpy

import numpy as np

In [4]:
#checking numpy version

print(np.__version__)

1.24.3


In [7]:
#creating a numpy array

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


task 1 import numpy, cek version, bikin contoh numpy, type data

In [10]:
import numpy as np

In [11]:
print(np.__version__)

1.24.3


In [12]:
a = np.array([1,1,2,3,5,8])
print(a)

[1 1 2 3 5 8]


In [13]:
print(type(a))

<class 'numpy.ndarray'>


Dimension in array

A dimension in arrays is one level of array depth (nested arrays)

In [15]:
#0-D arrays

import numpy as np
arr = np.array(42)
print(arr)

42


In [16]:
#1-D arrays

arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [19]:
#create 2-D arrays containing two arrays

arr = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(arr)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


Task 2 create 0-D, 1-D, 2-D

In [21]:
#0-D

import numpy as np
x = np.array("Data")
print(x)

Data


In [28]:
#1-D

x = np.array([1,1.2,True])
print(x)

[1.  1.2 1. ]


In [30]:
#2-D

x = np.array([[1,2,3],[2,3,4],[4,5,6]])
print(x)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [53]:
# check has many dimension the arrays here

a = np.array(42)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [11, 12, 13]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


SyntaxError: invalid non-printable character U+00A0 (3997147261.py, line 6)

In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=2)

print(arr)
print("number of dimension :", arr.ndim)

SyntaxError: invalid non-printable character U+00A0 (1076269906.py, line 6)

In [39]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])

2


In [40]:
#get third and fourth elements from the following array and add them

import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [42]:
#acces the element on the 2nd row, 5th column

import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,4])

10


Task 4

In [51]:
import numpy as np
x = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
print(x)
print(x[2,1] + x[1,2])
print("3rd coulmn and 3rd row on list:", x[2,2])

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
8
3rd coulmn and 3rd row on list: 5
